;;;; emitter.lisp - Core file I/O for crystallized source
;;;;
;;;; Writes S-expression forms to disk as readable Lisp source files.

(in-package #:autopoiesis.crystallize)

;;; ===================================================================
;;; File Emitter
;;; ===================================================================

(defun emit-to-file (forms output-path &key header)
  "Write S-expression forms to OUTPUT-PATH as readable Lisp source.
   FORMS is a list of S-expressions. HEADER is an optional string comment."
  (ensure-directories-exist output-path)
  (with-open-file (out output-path :direction :output
                                    :if-exists :supersede
                                    :if-does-not-exist :create
                                    :external-format :utf-8)
    (when header
      (format out ";;;; ~a~%;;;; Auto-generated by Autopoiesis crystallization engine~%~%" header))
    (let ((*print-readably* t)
          (*print-circle* t)
          (*print-array* t)
          (*print-length* nil)
          (*print-level* nil)
          (*package* (find-package :autopoiesis.core)))
      (dolist (form forms)
        (prin1 form out)
        (terpri out)
        (terpri out))))
  output-path)
