;;;; campaign.lisp - Research campaign orchestration
;;;;
;;;; Coordinates the three-step research flow:
;;;; 1. Plan approaches (one-shot Claude call)
;;;; 2. Run trials in parallel sandboxes
;;;; 3. Summarize and rank results
;;;;
;;;; Two execution modes:
;;;;   :tool-backed     - AP agentic-agent calls sandbox tools (sandbox-exec, etc.)
;;;;   :fully-sandboxed - Spawn a full agent CLI (e.g., claude) inside the sandbox

(in-package #:autopoiesis.research)

;;; ── Campaign data structures ───────────────────────────────────

(defclass research-campaign ()
  ((id :initarg :id
       :accessor campaign-id
       :initform (autopoiesis.core:make-uuid))
   (question :initarg :question
             :accessor campaign-question
             :documentation "The research question")
   (num-approaches :initarg :num-approaches
                   :accessor campaign-num-approaches
                   :initform 5)
   (approaches :initarg :approaches
               :accessor campaign-approaches
               :initform nil
               :documentation "List of approach alists generated by plan-approaches")
   (trials :accessor campaign-trials
           :initform nil
           :documentation "List of trial result plists")
   (summary :accessor campaign-summary
            :initform nil
            :documentation "Final ranked summary")
   (status :accessor campaign-status
           :initform :pending
           :documentation ":pending :planning :running :summarizing :complete :failed")
   (mode :initarg :mode
         :accessor campaign-mode
         :initform :tool-backed
         :documentation ":tool-backed or :fully-sandboxed")
   (layers :initarg :layers
           :accessor campaign-layers
           :initform '("000-base-alpine" "101-python")
           :documentation "Squashfs layers for trial sandboxes")
   (timeout :initarg :timeout
            :accessor campaign-timeout
            :initform 600
            :documentation "Per-trial timeout in seconds")
   (max-turns :initarg :max-turns
              :accessor campaign-max-turns
              :initform 15
              :documentation "Max agentic loop turns per trial (tool-backed mode)")
   (created-at :initform (get-universal-time)
               :accessor campaign-created-at))
  (:documentation "A research campaign: question -> approaches -> trials -> summary"))

;;; ── Step 1: Generate approaches ────────────────────────────────

(defun plan-approaches (campaign &key client)
  "Ask Claude to generate N different approaches for the research question.
   Returns list of approach alists."
  (setf (campaign-status campaign) :planning)
  (let* ((client (or client (autopoiesis.integration:make-claude-client)))
         (n (campaign-num-approaches campaign))
         (prompt (format nil "I have a research question I want to investigate by running ~A ~
parallel experiments in isolated Linux sandboxes (Alpine Linux with Python).

Research question: ~A

Generate exactly ~A different approaches to investigate this. ~
For each approach, provide:
1. name: A short descriptive name (2-4 words)
2. hypothesis: What this approach tests
3. setup: What packages to install (pip packages, space-separated)
4. script_outline: Brief description of what the script should do
5. evaluation: How to determine if this approach found something useful

Respond with ONLY a JSON array of objects. No markdown, no explanation. ~
Each object has keys: name, hypothesis, setup, script_outline, evaluation."
                         n (campaign-question campaign) n))
         (response (autopoiesis.integration:claude-complete
                    client
                    (list `(("role" . "user") ("content" . ,prompt)))
                    :system "You are a research assistant. Output only valid JSON.")))
    ;; Parse the JSON response
    (let* ((text (autopoiesis.integration:response-text response))
           ;; Strip markdown fences if Claude wraps them
           (clean-text (cl-ppcre:regex-replace-all
                        "^```(?:json)?\\s*|\\s*```$" text ""))
           (approaches (handler-case
                           (cl-json:decode-json-from-string clean-text)
                         (error (e)
                           (warn "Failed to parse approaches: ~A~%Raw text: ~A" e text)
                           nil))))
      (setf (campaign-approaches campaign)
            (or approaches
                ;; Fallback: create N generic approaches
                (loop for i from 0 below n
                      collect `((:name . ,(format nil "approach-~A" i))
                                (:hypothesis . "Generic investigation")
                                (:setup . "")
                                (:script--outline . "Investigate the question")
                                (:evaluation . "Check if results are meaningful")))))
      (campaign-approaches campaign))))

;;; ── Step 2a: Tool-backed trial ─────────────────────────────────
;;;
;;; Agent runs in AP, executes commands in sandbox via tool capabilities.

(defun make-trial-system-prompt (question approach)
  "Build the system prompt for a tool-backed trial agent."
  (format nil "You are a research agent investigating a specific approach to a research question.

RESEARCH QUESTION: ~A

YOUR APPROACH: ~A
HYPOTHESIS: ~A

YOUR TASK:
1. Install required packages using sandbox_install
2. Write your experiment code using sandbox_write_file (write to /workspace/)
3. Run it using sandbox_exec
4. Read and analyze the output
5. Write a FINDINGS REPORT as your final message

FINDINGS REPORT FORMAT:
## Approach: [name]
## Result: [SUCCESS/PARTIAL/FAILURE]
## Evidence: [what you found, with data]
## Confidence: [HIGH/MEDIUM/LOW]
## Next Steps: [what to investigate further if promising]

Be thorough but efficient. You have limited turns.
If an approach fails, document WHY it failed -- that is valuable data too."
          question
          (cdr (assoc :name approach))
          (cdr (assoc :hypothesis approach))))

(defun run-trial-tool-backed (campaign approach index &key client)
  "Run a single trial using an AP agentic-agent with sandbox tools.
   Returns a trial result plist."
  (let* ((sandbox-id (format nil "trial-~A-~A"
                             (campaign-id campaign) index))
         (layers (campaign-layers campaign))
         (timeout (campaign-timeout campaign))
         (start-time (get-universal-time))
         (result-plist nil))

    (handler-case
        (progn
          ;; Create sandbox
          (autopoiesis.sandbox:create-sandbox
           sandbox-id
           :layers layers
           :memory-mb 1024
           :cpu 2.0
           :max-lifetime-s (+ timeout 120))

          ;; Create workspace directory
          (autopoiesis.sandbox:exec-in-sandbox
           sandbox-id "mkdir -p /workspace" :timeout 5)

          ;; Run agentic agent with sandbox tools
          (let* ((system-prompt (make-trial-system-prompt
                                 (campaign-question campaign) approach))
                 (agent (autopoiesis.integration:make-agentic-agent
                         :name (format nil "trial-~A" index)
                         :system-prompt system-prompt
                         :capabilities (research-tool-capabilities)
                         :max-turns (campaign-max-turns campaign)))
                 ;; Init conversation context for the trial
                 (ctx (when autopoiesis.substrate:*store*
                        (autopoiesis.integration:init-conversation-context
                         agent :name (format nil "trial-~A-~A"
                                             (campaign-id campaign) index))))
                 ;; Bind the sandbox for this trial's tools
                 (*trial-sandbox-id* sandbox-id))
            (declare (ignore ctx))

            ;; Run the agent
            (let ((response (autopoiesis.integration:agentic-agent-prompt
                             agent
                             (format nil "Begin investigating: ~A~%~%~
                                          Packages to install: ~A~%~
                                          Approach: ~A"
                                     (cdr (assoc :name approach))
                                     (or (cdr (assoc :setup approach)) "none")
                                     (or (cdr (assoc :script--outline approach))
                                         "investigate")))))

              (setf result-plist
                    (list :index index
                          :approach-name (cdr (assoc :name approach))
                          :hypothesis (cdr (assoc :hypothesis approach))
                          :response response
                          :status :completed
                          :mode :tool-backed
                          :duration (- (get-universal-time) start-time)
                          :sandbox-id sandbox-id)))))

      (error (e)
        (setf result-plist
              (list :index index
                    :approach-name (cdr (assoc :name approach))
                    :hypothesis (cdr (assoc :hypothesis approach))
                    :response (format nil "Trial failed: ~A" e)
                    :status :failed
                    :mode :tool-backed
                    :duration (- (get-universal-time) start-time)
                    :sandbox-id sandbox-id))))

    ;; Always clean up sandbox
    (ignore-errors
      (autopoiesis.sandbox:destroy-sandbox sandbox-id))

    result-plist))

;;; ── Step 2b: Fully-sandboxed agent trial ───────────────────────
;;;
;;; An entire agent (e.g., Claude Code CLI) runs inside the sandbox.
;;; The agent has full access to the sandbox filesystem, can install
;;; anything, and operates autonomously. We capture its stdout as the
;;; trial result.

(defvar *sandboxed-agent-command* "claude"
  "Command to invoke the sandboxed agent CLI. Default: 'claude' (Claude Code).
   Can be customized per-trial or globally.")

(defun make-sandboxed-agent-prompt (question approach)
  "Build the prompt that gets piped to the sandboxed agent."
  (format nil "You are running inside an isolated Alpine Linux sandbox with Python available.

RESEARCH QUESTION: ~A

YOUR APPROACH: ~A
HYPOTHESIS: ~A

INSTRUCTIONS:
1. Install any packages you need (pip, apk, npm are available)
2. Write and run code to investigate the hypothesis
3. Analyze the results
4. Output a FINDINGS REPORT to /workspace/findings.md with this format:

## Approach: [name]
## Result: [SUCCESS/PARTIAL/FAILURE]
## Evidence: [what you found, with numbers/data]
## Confidence: [HIGH/MEDIUM/LOW]
## Next Steps: [what to investigate further if promising]

Work in /workspace/. Be thorough but efficient."
          question
          (cdr (assoc :name approach))
          (cdr (assoc :hypothesis approach))))

(defun run-trial-fully-sandboxed (campaign approach index &key agent-command)
  "Run a trial with a full agent running inside the sandbox.
   The agent CLI is invoked inside the sandbox and given the research prompt.
   Returns a trial result plist."
  (let* ((sandbox-id (format nil "trial-~A-~A"
                             (campaign-id campaign) index))
         (layers (campaign-layers campaign))
         (timeout (campaign-timeout campaign))
         (start-time (get-universal-time))
         (cmd (or agent-command *sandboxed-agent-command*))
         (result-plist nil))

    (handler-case
        (progn
          ;; Create sandbox with networking for the agent to call APIs
          (autopoiesis.sandbox:create-sandbox
           sandbox-id
           :layers layers
           :memory-mb 2048  ; agents need more memory
           :cpu 2.0
           :max-lifetime-s (+ timeout 120))

          ;; Create workspace
          (autopoiesis.sandbox:exec-in-sandbox
           sandbox-id "mkdir -p /workspace" :timeout 5)

          ;; Write the prompt file into the sandbox
          (let ((prompt (make-sandboxed-agent-prompt
                         (campaign-question campaign) approach)))
            (autopoiesis.sandbox:exec-in-sandbox
             sandbox-id
             (format nil "cat > /workspace/prompt.txt << 'PROMPT_EOF'~%~A~%PROMPT_EOF"
                     prompt)
             :timeout 5))

          ;; Run the agent inside the sandbox
          ;; The agent command reads the prompt and works autonomously
          (let ((agent-result
                  (autopoiesis.sandbox:exec-in-sandbox
                   sandbox-id
                   (format nil "cd /workspace && ~A --print \"$(cat /workspace/prompt.txt)\" 2>/workspace/agent-stderr.log; echo '---EXIT:' $?"
                           cmd)
                   :timeout timeout
                   :workdir "/workspace")))

            ;; Try to read the findings report
            (let ((findings-result
                    (autopoiesis.sandbox:exec-in-sandbox
                     sandbox-id
                     "cat /workspace/findings.md 2>/dev/null || echo 'No findings.md produced'"
                     :timeout 5)))

              (let ((findings (squashd:exec-result-stdout findings-result))
                    (agent-output (squashd:exec-result-stdout agent-result))
                    (agent-stderr (squashd:exec-result-stderr agent-result)))

                (setf result-plist
                      (list :index index
                            :approach-name (cdr (assoc :name approach))
                            :hypothesis (cdr (assoc :hypothesis approach))
                            :response (if (and findings
                                               (> (length findings) 30)
                                               (not (search "No findings.md" findings)))
                                          findings
                                          ;; Fall back to agent stdout if no findings.md
                                          agent-output)
                            :agent-output agent-output
                            :agent-stderr agent-stderr
                            :status (if (zerop (squashd:exec-result-exit-code agent-result))
                                        :completed :failed)
                            :mode :fully-sandboxed
                            :duration (- (get-universal-time) start-time)
                            :sandbox-id sandbox-id))))))

      (error (e)
        (setf result-plist
              (list :index index
                    :approach-name (cdr (assoc :name approach))
                    :hypothesis (cdr (assoc :hypothesis approach))
                    :response (format nil "Trial failed: ~A" e)
                    :status :failed
                    :mode :fully-sandboxed
                    :duration (- (get-universal-time) start-time)
                    :sandbox-id sandbox-id))))

    ;; Always clean up
    (ignore-errors
      (autopoiesis.sandbox:destroy-sandbox sandbox-id))

    result-plist))

;;; ── Step 2: Run all trials ─────────────────────────────────────

(defun run-trial (campaign approach index &key client agent-command)
  "Run a single trial, dispatching to the correct mode."
  (case (campaign-mode campaign)
    (:fully-sandboxed
     (run-trial-fully-sandboxed campaign approach index
                                 :agent-command agent-command))
    (otherwise
     (run-trial-tool-backed campaign approach index :client client))))

(defun run-all-trials (campaign &key client agent-command)
  "Run all trials in parallel using threads.
   Updates campaign-trials when all complete."
  (setf (campaign-status campaign) :running)
  (let* ((approaches (campaign-approaches campaign))
         (n (length approaches))
         (results (make-array n :initial-element nil))
         (lock (bt:make-lock "trial-results"))
         (completed (bt:make-condition-variable :name "trials-done"))
         (done-count 0)
         ;; Capture substrate bindings for child threads
         (captured-substrate autopoiesis.substrate:*substrate*)
         (captured-store autopoiesis.substrate:*store*)
         (captured-intern autopoiesis.substrate::*intern-table*)
         (captured-resolve autopoiesis.substrate::*resolve-table*)
         (captured-index autopoiesis.substrate::*index*)
         (captured-hooks autopoiesis.substrate::*hooks*))

    ;; Spawn one thread per trial
    (loop for approach in approaches
          for i from 0
          do (let ((my-approach approach)
                   (my-index i))
               (bt:make-thread
                (lambda ()
                  ;; Rebind substrate specials in child thread
                  (let ((autopoiesis.substrate:*substrate* captured-substrate)
                        (autopoiesis.substrate:*store* captured-store)
                        (autopoiesis.substrate::*intern-table* captured-intern)
                        (autopoiesis.substrate::*resolve-table* captured-resolve)
                        (autopoiesis.substrate::*index* captured-index)
                        (autopoiesis.substrate::*hooks* captured-hooks))
                    (let ((result (run-trial campaign my-approach my-index
                                             :client client
                                             :agent-command agent-command)))
                      (bt:with-lock-held (lock)
                        (setf (aref results my-index) result)
                        (incf done-count)
                        (when (= done-count n)
                          (bt:condition-notify completed))))))
                :name (format nil "trial-~A" i))))

    ;; Wait for all trials to complete
    (bt:with-lock-held (lock)
      (loop while (< done-count n)
            do (bt:condition-wait completed lock
                                  :timeout (+ (campaign-timeout campaign) 120))))

    ;; Collect results
    (setf (campaign-trials campaign)
          (coerce results 'list))
    (campaign-trials campaign)))

;;; ── Step 3: Summarize results ──────────────────────────────────

(defun summarize-results (campaign &key client)
  "Ask Claude to rank and summarize all trial results.
   Returns a summary string."
  (setf (campaign-status campaign) :summarizing)
  (let* ((client (or client (autopoiesis.integration:make-claude-client)))
         (trial-reports
           (format nil "~{~A~^~%~%---~%~%~}"
                   (loop for trial in (campaign-trials campaign)
                         collect (format nil "## Trial ~A: ~A~%Status: ~A | Mode: ~A | Duration: ~As~%~%~A"
                                         (getf trial :index)
                                         (getf trial :approach-name)
                                         (getf trial :status)
                                         (getf trial :mode)
                                         (getf trial :duration)
                                         (getf trial :response)))))
         (prompt (format nil "I ran ~A parallel research trials to investigate:

~A

Here are all the trial reports:

~A

Please provide:
1. A RANKED summary (best to worst) with 1-2 sentence justification each
2. An overall VERDICT: was anything actionable found?
3. RECOMMENDED NEXT STEPS if any approach showed promise

Be concise and direct. I want to know: should I pursue any of these further?"
                         (length (campaign-trials campaign))
                         (campaign-question campaign)
                         trial-reports))
         (response (autopoiesis.integration:claude-complete
                    client
                    (list `(("role" . "user") ("content" . ,prompt)))
                    :system "You are evaluating research results. Be direct and honest about what worked and what didn't.")))
    (let ((summary (autopoiesis.integration:response-text response)))
      (setf (campaign-summary campaign) summary)
      (setf (campaign-status campaign) :complete)
      summary)))

;;; ── Standalone sandboxed agent runner ──────────────────────────
;;;
;;; For running a single fully-sandboxed agent outside of a campaign.

(defun run-sandboxed-agent (prompt &key (layers '("000-base-alpine" "101-python"))
                                        (timeout 600)
                                        (memory-mb 2048)
                                        (agent-command *sandboxed-agent-command*)
                                        (stream *standard-output*))
  "Run a single fully-sandboxed agent with the given prompt.
   The agent CLI runs entirely inside a sandbox with full filesystem access.

   Returns a plist with :stdout, :stderr, :exit-code, :findings, :duration.

   Example:
     (run-sandboxed-agent
       \"Write a Python script that scrapes the top HN stories and analyzes sentiment.\"
       :timeout 300)"
  (unless autopoiesis.sandbox:*sandbox-manager*
    (error "Sandbox manager not initialized."))

  (let* ((sandbox-id (format nil "agent-~A" (autopoiesis.core:make-uuid)))
         (start-time (get-universal-time)))

    (format stream "~%Creating sandbox ~A...~%" sandbox-id)

    (unwind-protect
         (handler-case
             (progn
               (autopoiesis.sandbox:create-sandbox
                sandbox-id
                :layers layers
                :memory-mb memory-mb
                :cpu 2.0
                :max-lifetime-s (+ timeout 120))

               (autopoiesis.sandbox:exec-in-sandbox
                sandbox-id "mkdir -p /workspace" :timeout 5)

               ;; Write prompt
               (autopoiesis.sandbox:exec-in-sandbox
                sandbox-id
                (format nil "cat > /workspace/prompt.txt << 'PROMPT_EOF'~%~A~%PROMPT_EOF"
                        prompt)
                :timeout 5)

               (format stream "Running agent (~A) in sandbox...~%" agent-command)

               ;; Run agent
               (let ((result (autopoiesis.sandbox:exec-in-sandbox
                              sandbox-id
                              (format nil "cd /workspace && ~A --print \"$(cat /workspace/prompt.txt)\""
                                      agent-command)
                              :timeout timeout
                              :workdir "/workspace")))

                 ;; Try to read findings
                 (let* ((findings-result
                          (autopoiesis.sandbox:exec-in-sandbox
                           sandbox-id
                           "cat /workspace/findings.md 2>/dev/null || echo ''"
                           :timeout 5))
                        (findings (squashd:exec-result-stdout findings-result))
                        (duration (- (get-universal-time) start-time)))

                   (format stream "~%Agent completed in ~As (exit code: ~A)~%"
                           duration (squashd:exec-result-exit-code result))

                   (list :stdout (squashd:exec-result-stdout result)
                         :stderr (squashd:exec-result-stderr result)
                         :exit-code (squashd:exec-result-exit-code result)
                         :findings (when (and findings (> (length findings) 0))
                                     findings)
                         :duration duration
                         :sandbox-id sandbox-id))))

           (error (e)
             (format stream "~%Error: ~A~%" e)
             (list :error (format nil "~A" e)
                   :duration (- (get-universal-time) start-time))))

      ;; Always cleanup
      (ignore-errors
        (autopoiesis.sandbox:destroy-sandbox sandbox-id)))))
